### ISSUE TITLE
Reliability of services

### ISSUE THREAD

**Issue by xinthose** [molnarmark/validator-pizza-node#2]
Hello.  Thank you for providing this valuable free service.  Should this service be used for production level code?  What servers are hosting your API?  I just want to make sure that your service is reliable if I plan on integrating it into my website's user signup process.  I was recently the target of many accounts being created from `tmpbox.net`.

**Comment by molnarmark** [comment]
Hi.

I have nothing to do with the original API, I only built a Node.js library around it, so I can't answer those questions for you.
The creator of [validator.pizza](https://validator.pizza) is [Thomas Petracco](https://www.tompec.com/).

**Comment by xinthose** [comment]
Whoops.  You are correct.  Thank you.
